apiVersion: v2
description: Mailcatcher
name: mailcatcher
version: 0.2.0
appVersion: 0.10.0
type: application
keywords:
  - mailcatcher
  - mail
maintainers:
  - name: Brian Matthews
    email: brian.matthews@buralotech.com
icon: https://mailcatcher.me/logo.png