apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailcatcher.fullname" . }}
  labels:
    {{- include "mailcatcher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.smtp }}
      targetPort: smtp
      protocol: TCP
      name: smtp
  selector:
    {{- include "mailcatcher.selectorLabels" . | nindent 4 }}
